version: '3.9'

services:
    postgres:
        image: postgres:15-alpine
        container_name: ${APP_NAME}-postgres
        restart: unless-stopped
        tty: true
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - TZ=${POSTGRES_TIMEZONE}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
        volumes:
            - ${DOCKER_DATA}/postgres:/var/lib/postgresql/data:rw,delegated
        networks:
            - db
    adminerdg:
        build:
            context: ./docker/adminerdg
            args:
                - ADMINER_DG_VERSION=${ADMINER_DG_VERSION}
        container_name: ${APP_NAME}-adminerdg
        ports:
            - "${ADMINER_PORT}:8080"
        networks:
            - db

networks:
    db:
        driver: bridge
